services:
  duckdb:
    image: duckdb/duckdb
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./workspace:/workspace
      - ./home:/home/duckdb
    environment:
      - HOME=/home/duckdb
    ports:
      - "4213:4213"
    stdin_open: true
    tty: true
    networks:
      - dbt_repo_network

networks:
  dbt_repo_network:
    external: true