version: 2

sources:
  - name: public
    database: postgres
    schema: public
    tables:
      - name: df_Customers
      - name: df_OrderItems
      - name: df_Orders
      - name: df_Payments
      - name: df_Products